/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteImport } from './routes/access'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as EnergyRouteImport } from './routes/energy'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HouseholdRouteImport } from './routes/household'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as MonthRouteImport } from './routes/month'
import { Route as MoreRouteImport } from './routes/more'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as StartRouteImport } from './routes/start'
import { Route as StarterRouteImport } from './routes/starter'
import { Route as StoreCreditRouteImport } from './routes/store-credit'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThanksRouteImport } from './routes/thanks'
import { Route as WeekRouteImport } from './routes/week'
import { Route as GuideIndexRouteImport } from './routes/guide.index'
import { Route as GuideSlugRouteImport } from './routes/guide.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyRoute = EnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRoute = HouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthRoute = MonthRouteImport.update({
  id: '/month',
  path: '/month',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const StarterRoute = StarterRouteImport.update({
  id: '/starter',
  path: '/starter',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreCreditRoute = StoreCreditRouteImport.update({
  id: '/store-credit',
  path: '/store-credit',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanksRoute = ThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekRoute = WeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideIndexRoute = GuideIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuideRoute,
} as any)
const GuideSlugRoute = GuideSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuideRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/buy': typeof BuyRoute
  '/daily': typeof DailyRoute
  '/energy': typeof EnergyRoute
  '/guide': typeof GuideRouteWithChildren
  '/household': typeof HouseholdRoute
  '/intro': typeof IntroRoute
  '/month': typeof MonthRoute
  '/more': typeof MoreRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/start': typeof StartRoute
  '/starter': typeof StarterRoute
  '/store-credit': typeof StoreCreditRoute
  '/terms': typeof TermsRoute
  '/thanks': typeof ThanksRoute
  '/week': typeof WeekRoute
  '/guide/$slug': typeof GuideSlugRoute
  '/guide/': typeof GuideIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/buy': typeof BuyRoute
  '/daily': typeof DailyRoute
  '/energy': typeof EnergyRoute
  '/household': typeof HouseholdRoute
  '/intro': typeof IntroRoute
  '/month': typeof MonthRoute
  '/more': typeof MoreRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/start': typeof StartRoute
  '/starter': typeof StarterRoute
  '/store-credit': typeof StoreCreditRoute
  '/terms': typeof TermsRoute
  '/thanks': typeof ThanksRoute
  '/week': typeof WeekRoute
  '/guide/$slug': typeof GuideSlugRoute
  '/guide': typeof GuideIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/buy': typeof BuyRoute
  '/daily': typeof DailyRoute
  '/energy': typeof EnergyRoute
  '/guide': typeof GuideRouteWithChildren
  '/household': typeof HouseholdRoute
  '/intro': typeof IntroRoute
  '/month': typeof MonthRoute
  '/more': typeof MoreRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/start': typeof StartRoute
  '/starter': typeof StarterRoute
  '/store-credit': typeof StoreCreditRoute
  '/terms': typeof TermsRoute
  '/thanks': typeof ThanksRoute
  '/week': typeof WeekRoute
  '/guide/$slug': typeof GuideSlugRoute
  '/guide/': typeof GuideIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/buy'
    | '/daily'
    | '/energy'
    | '/guide'
    | '/household'
    | '/intro'
    | '/month'
    | '/more'
    | '/privacy'
    | '/setup'
    | '/start'
    | '/starter'
    | '/store-credit'
    | '/terms'
    | '/thanks'
    | '/week'
    | '/guide/$slug'
    | '/guide/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/buy'
    | '/daily'
    | '/energy'
    | '/household'
    | '/intro'
    | '/month'
    | '/more'
    | '/privacy'
    | '/setup'
    | '/start'
    | '/starter'
    | '/store-credit'
    | '/terms'
    | '/thanks'
    | '/week'
    | '/guide/$slug'
    | '/guide'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/buy'
    | '/daily'
    | '/energy'
    | '/guide'
    | '/household'
    | '/intro'
    | '/month'
    | '/more'
    | '/privacy'
    | '/setup'
    | '/start'
    | '/starter'
    | '/store-credit'
    | '/terms'
    | '/thanks'
    | '/week'
    | '/guide/$slug'
    | '/guide/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  BuyRoute: typeof BuyRoute
  DailyRoute: typeof DailyRoute
  EnergyRoute: typeof EnergyRoute
  GuideRoute: typeof GuideRouteWithChildren
  HouseholdRoute: typeof HouseholdRoute
  IntroRoute: typeof IntroRoute
  MonthRoute: typeof MonthRoute
  MoreRoute: typeof MoreRoute
  PrivacyRoute: typeof PrivacyRoute
  SetupRoute: typeof SetupRoute
  StartRoute: typeof StartRoute
  StarterRoute: typeof StarterRoute
  StoreCreditRoute: typeof StoreCreditRoute
  TermsRoute: typeof TermsRoute
  ThanksRoute: typeof ThanksRoute
  WeekRoute: typeof WeekRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy': {
      id: '/energy'
      path: '/energy'
      fullPath: '/energy'
      preLoaderRoute: typeof EnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household': {
      id: '/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof HouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/month': {
      id: '/month'
      path: '/month'
      fullPath: '/month'
      preLoaderRoute: typeof MonthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starter': {
      id: '/starter'
      path: '/starter'
      fullPath: '/starter'
      preLoaderRoute: typeof StarterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-credit': {
      id: '/store-credit'
      path: '/store-credit'
      fullPath: '/store-credit'
      preLoaderRoute: typeof StoreCreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanks': {
      id: '/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof ThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/week': {
      id: '/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof WeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/': {
      id: '/guide/'
      path: '/'
      fullPath: '/guide/'
      preLoaderRoute: typeof GuideIndexRouteImport
      parentRoute: typeof GuideRoute
    }
    '/guide/$slug': {
      id: '/guide/$slug'
      path: '/$slug'
      fullPath: '/guide/$slug'
      preLoaderRoute: typeof GuideSlugRouteImport
      parentRoute: typeof GuideRoute
    }
  }
}

interface GuideRouteChildren {
  GuideSlugRoute: typeof GuideSlugRoute
  GuideIndexRoute: typeof GuideIndexRoute
}

const GuideRouteChildren: GuideRouteChildren = {
  GuideSlugRoute: GuideSlugRoute,
  GuideIndexRoute: GuideIndexRoute,
}

const GuideRouteWithChildren = GuideRoute._addFileChildren(GuideRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  BuyRoute: BuyRoute,
  DailyRoute: DailyRoute,
  EnergyRoute: EnergyRoute,
  GuideRoute: GuideRouteWithChildren,
  HouseholdRoute: HouseholdRoute,
  IntroRoute: IntroRoute,
  MonthRoute: MonthRoute,
  MoreRoute: MoreRoute,
  PrivacyRoute: PrivacyRoute,
  SetupRoute: SetupRoute,
  StartRoute: StartRoute,
  StarterRoute: StarterRoute,
  StoreCreditRoute: StoreCreditRoute,
  TermsRoute: TermsRoute,
  ThanksRoute: ThanksRoute,
  WeekRoute: WeekRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
